import React from "react";
import {
  SiFigma,
  SiFramer,
  SiNotion,
  SiReact,
  SiTypescript,
  SiJavascript,
  SiAngular,
  SiTailwindcss,
  SiHtml5,
  SiCss3,
  SiNodedotjs,
  SiPython,
  SiDotnet,
  SiSpringboot,
  SiWordpress,
  SiWebflow,
  SiVite,
  SiNextdotjs,
  SiPostgresql,
  SiAdobexd,
  SiHotjar,
  SiOpenai,
  SiGit,
  SiGithub,
  SiDocker,
  SiBootstrap,
} from "react-icons/si";
import { VscAzureDevops } from "react-icons/vsc";
import { DiJava, DiSqllite } from "react-icons/di";
const iconMap: Record<
  string,
  React.ComponentType<{ size?: number; style?: React.CSSProperties }>
> = {
  Figma: SiFigma,
  "Adobe XD": SiAdobexd,
  Framer: SiFramer,
  Notion: SiNotion,
  Hotjar: SiHotjar,
  ChatGPT: SiOpenai,
  React: SiReact,
  TypeScript: SiTypescript,
  JavaScript: SiJavascript,
  Angular: SiAngular,
  "Tailwind CSS": SiTailwindcss,
  HTML: SiHtml5,
  CSS: SiCss3,
  "Node.js": SiNodedotjs,
  Python: SiPython,
  ".NET": SiDotnet,
  "Spring Boot": SiSpringboot,
  WordPress: SiWordpress,
  Webflow: SiWebflow,
  Vite: SiVite,
  "Next.js": SiNextdotjs,
  "Framer Motion": SiFramer,
  PostgreSQL: SiPostgresql,
  "Azure DevOps": VscAzureDevops,
  Git: SiGit,
  GitHub: SiGithub,
  Docker: SiDocker,
  Java: DiJava,
  SQL: DiSqllite,
  Bootstrap: SiBootstrap,
};

export const getTechIcon = (
  name: string,
): React.ComponentType<{ size?: number; style?: React.CSSProperties }> | null =>
  iconMap[name] ?? null;
